# Generated by Django 5.1.7 on 2025-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
